package com.dglazewski.shop.api.enums;

public enum Status {
    RECORD_HAS_NOT_VALID_FIELDS,
    RECORD_DOESNT_EXIST,
    UNKNOWN_DATABASE_ERROR,
    RECORD_ALREADY_EXIST,
    RECORD_CREATED_SUCCESSFULLY,
    RECORD_RETRIEVED_SUCCESSFULLY,
    RECORD_UPDATED_SUCCESSFULLY,
    RECORD_DELETED_SUCCESSFULLY,
    USER_VERIFICATION_SUCCESS,
    USER_VERIFICATION_FAILURE,
}
